"""Generates the CWD ``mc_constants.py`` proxy from a fetched catalog
(wire-format-design §7.2.1, DECISIONS 2026-07-29-04).

This implements 12-python-client/mc-constants-design_ja.md's project-local
CWD generation and ``sys.path`` guarantee from a live ``catalog.get`` fetch.
The projection is intentionally not bundled: since the registry can include
mods, there is no fixed set of "all versions" to ship, so generation only
happens once a live session has a ``catalogHash`` to key it by (see
:meth:`mc_remote.minecraft.Minecraft.sync_constants`).

Only ``block``/``entity``/``particle`` come from the catalog; world
constants (``y_sea`` etc.) are a separate ``hello`` field. The caller folds
those in via ``world_info`` so the generated file still satisfies the
``from mc_constants import block, entity, particle, world_info`` shape the
guide documents.
"""
import keyword
import re

_IDENTIFIER_SUB = re.compile(r"[^0-9A-Za-z_]")


def _to_identifier(name, seen):
    """Turn a catalog id (``"minecraft:oak_log"``, ``"modid:thing"``) into a
    valid, collision-resistant Python identifier: strip the namespace,
    upper-case, non-identifier characters become ``_``. A leading digit gets
    a ``_`` prefix, a Python-keyword collision gets a trailing ``_``, and a
    same-local-name collision across namespaces (e.g. two mods both exposing
    ``thing``) is disambiguated with a numeric suffix rather than silently
    overwritten."""
    local = name.split(":", 1)[-1]
    ident = _IDENTIFIER_SUB.sub("_", local).upper()
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    if keyword.iskeyword(ident.lower()):
        ident = f"{ident}_"
    if ident in seen:
        seen[ident] += 1
        ident = f"{ident}_{seen[ident]}"
    else:
        seen[ident] = 0
    return ident


def _class_body(catalog_ids):
    seen = {}
    lines = [
        f"    {_to_identifier(full_id, seen)} = {full_id!r}"
        for full_id in sorted(catalog_ids)
    ]
    return "\n".join(lines) if lines else "    pass"


def generate_source(catalog, mc_version, catalog_hash, world_info=None):
    """Build the ``mc_constants.py`` source text for ``catalog`` (a
    :func:`mc_remote.catalog.validate_catalog`-checked ``catalog.get``
    result). ``world_info`` is an optional ``{NAME: value}`` mapping of
    extra module-level constants (e.g. ``{"Y_SEA": 63}`` from the connected
    session's ``hello`` response) folded into a ``world_info`` class."""
    block_ids = catalog["block"].keys()
    entity_ids = catalog["entity"].keys()
    particle_ids = catalog["particle"].keys()

    header = (
        "# ==========================================\n"
        "# This file is auto-generated by mc_remote.Minecraft.sync_constants().\n"
        "# Do not edit -- it is regenerated whenever the connected server's\n"
        "# catalogHash changes (a different mc_version or mod registry).\n"
        f"#   mc_version   = {mc_version!r}\n"
        f"#   catalogHash  = {catalog_hash!r}\n"
        f"#   block/entity/particle counts = "
        f"{len(block_ids)}/{len(entity_ids)}/{len(particle_ids)}\n"
        "# ==========================================\n\n"
    )

    parts = [
        header,
        f"MC_VERSION = {mc_version!r}\n",
        f"CATALOG_HASH = {catalog_hash!r}\n\n\n",
        "class block:\n" + _class_body(block_ids) + "\n\n\n",
        "class entity:\n" + _class_body(entity_ids) + "\n\n\n",
        "class particle:\n" + _class_body(particle_ids) + "\n",
    ]
    if world_info:
        body = "\n".join(f"    {key} = {value!r}" for key, value in world_info.items())
        parts.append("\n\nclass world_info:\n" + (body or "    pass") + "\n")
    return "".join(parts)
